[tool.poetry]
name = "fastcrud"
version = "0.1.0"
description = "FastCRUD is a Python package that streamlines CRUD operations in FastAPI, offering easy integration with SQLAlchemy and Pydantic for efficient API development."
authors = ["Igor Magalhaes <igor.magalhaes.r@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
SQLAlchemy = "^2.0.21"
pydantic = "^2.4.1"
SQLAlchemy-Utils = "^0.41.1"
fastapi = "^0.109.0"
uvicorn = "^0.25.0"

[tool.poetry.dev-dependencies]
pytest = "^7.4.4"
aiosqlite = "^0.19.0"
greenlet = "^3.0.3"
httpx = "^0.26.0"
pytest-asyncio = "^0.23.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
